import { Exercise, MuscleGroup } from "@/types";

const getExerciseImage = (muscleGroup: string, index: number): string => {
  const images: Record<string, string[]> = {
    chest: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
      "https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=400",
      "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400",
      "https://images.unsplash.com/photo-1605296867424-35fc25c9212a?w=400",
    ],
    back: [
      "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400",
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400",
      "https://images.unsplash.com/photo-1583454155184-1dad885a6ddf?w=400",
    ],
    shoulders: [
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400",
      "https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=400",
      "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
    ],
    biceps: [
      "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400",
      "https://images.unsplash.com/photo-1532384816664-01b8b7238c8d?w=400",
      "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400",
      "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400",
    ],
    triceps: [
      "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400",
      "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
      "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400",
    ],
    quadriceps: [
      "https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400",
      "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400",
      "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
    ],
    hamstrings: [
      "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400",
      "https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400",
      "https://images.unsplash.com/photo-1605296867424-35fc25c9212a?w=400",
    ],
    glutes: [
      "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400",
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400",
      "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400",
      "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400",
    ],
    calves: [
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400",
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400",
      "https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=400",
      "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400",
    ],
    abs: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
      "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400",
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400",
    ],
  };

  const muscleImages = images[muscleGroup.toLowerCase()] || images.chest;
  return muscleImages[index % muscleImages.length];
};

export const EXERCISES: Exercise[] = [
  {
    id: "ex_0001",
    name: "Barbell Bench Press",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Step 1: Lie flat on bench with feet on floor. Step 2: Grip bar slightly wider than shoulder width. Step 3: Lower bar to chest with control. Step 4: Press bar up explosively.",
    photo: getExerciseImage("chest", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0002",
    name: "Bent Over Barbell Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps", "shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Step 1: Hinge at hips with flat back. Step 2: Pull weight to hip with elbow tight. Step 3: Control the descent. Step 4: Maintain form throughout.",
    photo: getExerciseImage("back", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0003",
    name: "Overhead Dumbbell Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps", "chest"],
    equipment: "machine",
    difficulty: "advanced",
    instructions: "Step 1: Sit or stand with weights at shoulder height. Step 2: Press weights overhead. Step 3: Control descent back to start. Step 4: Keep core tight.",
    photo: getExerciseImage("shoulders", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0004",
    name: "Cable Bicep Curl",
    muscleGroup: "biceps",
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Step 1: Stand at cable machine with straight bar. Step 2: Curl bar up with control. Step 3: Squeeze at top. Step 4: Lower slowly.",
    photo: getExerciseImage("biceps", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0005",
    name: "Bodyweight Dips",
    muscleGroup: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Step 1: Support body on parallel bars. Step 2: Lower body with control. Step 3: Push back up explosively. Step 4: Keep elbows close.",
    photo: getExerciseImage("triceps", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0006",
    name: "Barbell Back Squat",
    muscleGroup: "quadriceps",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "band",
    difficulty: "advanced",
    instructions: "Step 1: Bar on upper back, feet shoulder width. Step 2: Squat down keeping chest up. Step 3: Drive through heels to stand. Step 4: Maintain tight core.",
    photo: getExerciseImage("quadriceps", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0007",
    name: "Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "kettlebell",
    difficulty: "beginner",
    instructions: "Step 1: Hold bar at hip level. Step 2: Hinge at hips lowering bar. Step 3: Feel stretch in hamstrings. Step 4: Return to start position.",
    photo: getExerciseImage("hamstrings", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0008",
    name: "Hip Thrust",
    muscleGroup: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "bench",
    difficulty: "intermediate",
    instructions: "Step 1: Upper back on bench, bar over hips. Step 2: Drive hips up squeezing glutes. Step 3: Hold at top. Step 4: Lower with control.",
    photo: getExerciseImage("glutes", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0009",
    name: "Standing Calf Raise",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Step 1: Stand with toes on platform. Step 2: Raise heels as high as possible. Step 3: Hold at top. Step 4: Lower with control.",
    photo: getExerciseImage("calves", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0010",
    name: "Cable Crunch",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Step 1: Kneel facing cable machine. Step 2: Crunch down bringing elbows to knees. Step 3: Control movement. Step 4: Return to start.",
    photo: getExerciseImage("abs", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0011",
    name: "Incline Dumbbell Press",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "machine",
    difficulty: "intermediate",
    instructions: "Step 1: Set bench to 30-45 degrees. Step 2: Press dumbbells up. Step 3: Control the descent. Step 4: Keep shoulder blades retracted.",
    photo: getExerciseImage("chest", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0012",
    name: "Lat Pulldown",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    difficulty: "advanced",
    instructions: "Step 1: Sit at lat machine with wide grip. Step 2: Pull bar to upper chest. Step 3: Squeeze shoulder blades. Step 4: Control the return.",
    photo: getExerciseImage("back", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0013",
    name: "Lateral Raise",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Step 1: Hold dumbbells at sides. Step 2: Raise arms to shoulder height. Step 3: Lead with elbows. Step 4: Lower with control.",
    photo: getExerciseImage("shoulders", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0014",
    name: "Hammer Curl",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "band",
    difficulty: "intermediate",
    instructions: "Step 1: Hold dumbbells with neutral grip. Step 2: Curl up keeping wrists straight. Step 3: Squeeze at top. Step 4: Lower slowly.",
    photo: getExerciseImage("biceps", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0015",
    name: "Overhead Tricep Extension",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "kettlebell",
    difficulty: "advanced",
    instructions: "Step 1: Hold weight overhead with both hands. Step 2: Lower behind head. Step 3: Extend arms overhead. Step 4: Keep elbows close.",
    photo: getExerciseImage("triceps", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0016",
    name: "Leg Extension",
    muscleGroup: "quadriceps",
    secondaryMuscles: [],
    equipment: "bench",
    difficulty: "beginner",
    instructions: "Step 1: Sit in machine with shins against pad. Step 2: Extend legs fully. Step 3: Squeeze quads at top. Step 4: Lower with control.",
    photo: getExerciseImage("quadriceps", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0017",
    name: "Lying Leg Curl",
    muscleGroup: "hamstrings",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Step 1: Lie face down on machine. Step 2: Curl legs toward glutes. Step 3: Squeeze hamstrings. Step 4: Lower slowly.",
    photo: getExerciseImage("hamstrings", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0018",
    name: "Cable Kickback",
    muscleGroup: "glutes",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "advanced",
    instructions: "Step 1: Attach ankle strap to cable. Step 2: Kick leg back squeezing glutes. Step 3: Control movement. Step 4: Return to start.",
    photo: getExerciseImage("glutes", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0019",
    name: "Seated Calf Raise",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Step 1: Sit with knees under pads. Step 2: Raise heels as high as possible. Step 3: Hold at top. Step 4: Lower with control.",
    photo: getExerciseImage("calves", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0020",
    name: "Hanging Leg Raise",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "intermediate",
    instructions: "Step 1: Hang from pull-up bar. Step 2: Raise legs to parallel. Step 3: Control the movement. Step 4: Lower with control.",
    photo: getExerciseImage("abs", 1),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0021",
    name: "Decline Push-Up",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Step 1: Feet elevated on bench. Step 2: Lower chest to ground. Step 3: Push up explosively. Step 4: Keep core tight.",
    photo: getExerciseImage("chest", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0022",
    name: "Resistance Band Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "band",
    difficulty: "beginner",
    instructions: "Step 1: Anchor band at chest height. Step 2: Pull handles to sides. Step 3: Squeeze shoulder blades. Step 4: Control return.",
    photo: getExerciseImage("back", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0023",
    name: "Kettlebell Shoulder Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "kettlebell",
    difficulty: "intermediate",
    instructions: "Step 1: Clean kettlebell to shoulder. Step 2: Press overhead. Step 3: Lock out arm. Step 4: Lower with control.",
    photo: getExerciseImage("shoulders", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0024",
    name: "Preacher Curl",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "bench",
    difficulty: "advanced",
    instructions: "Step 1: Sit at preacher bench. Step 2: Curl weight up. Step 3: Squeeze biceps at top. Step 4: Lower slowly.",
    photo: getExerciseImage("biceps", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0025",
    name: "Close-Grip Bench Press",
    muscleGroup: "triceps",
    secondaryMuscles: ["chest"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Step 1: Grip bar shoulder width. Step 2: Lower to chest keeping elbows in. Step 3: Press up explosively. Step 4: Lock out triceps.",
    photo: getExerciseImage("triceps", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0026",
    name: "Goblet Squat",
    muscleGroup: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Step 1: Hold dumbbell at chest. Step 2: Squat down keeping chest up. Step 3: Drive through heels. Step 4: Stand fully.",
    photo: getExerciseImage("quadriceps", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0027",
    name: "Nordic Hamstring Curl",
    muscleGroup: "hamstrings",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "advanced",
    instructions: "Step 1: Anchor feet and kneel. Step 2: Lower body forward with control. Step 3: Catch yourself with hands. Step 4: Pull back using hamstrings.",
    photo: getExerciseImage("hamstrings", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0028",
    name: "Bulgarian Split Squat",
    muscleGroup: "glutes",
    secondaryMuscles: ["quadriceps"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Step 1: Rear foot elevated on bench. Step 2: Squat down on front leg. Step 3: Drive through front heel. Step 4: Stand fully.",
    photo: getExerciseImage("glutes", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0029",
    name: "Jump Rope",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Step 1: Hold rope handles. Step 2: Jump rhythmically. Step 3: Land on balls of feet. Step 4: Maintain steady pace.",
    photo: getExerciseImage("calves", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0030",
    name: "Russian Twist",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "band",
    difficulty: "advanced",
    instructions: "Step 1: Sit with feet elevated. Step 2: Rotate torso side to side. Step 3: Touch ground each side. Step 4: Keep core engaged.",
    photo: getExerciseImage("abs", 2),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0031",
    name: "Kettlebell Swing",
    muscleGroup: "glutes",
    secondaryMuscles: ["hamstrings", "back"],
    equipment: "kettlebell",
    difficulty: "beginner",
    instructions: "Step 1: Hinge and swing kettlebell back. Step 2: Drive hips forward explosively. Step 3: Swing to chest height. Step 4: Control descent.",
    photo: getExerciseImage("glutes", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0032",
    name: "One-Arm Dumbbell Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "bench",
    difficulty: "intermediate",
    instructions: "Step 1: Support body on bench. Step 2: Pull dumbbell to hip. Step 3: Squeeze lat at top. Step 4: Lower with control.",
    photo: getExerciseImage("back", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0033",
    name: "Front Raise",
    muscleGroup: "shoulders",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Step 1: Hold dumbbells at thighs. Step 2: Raise arms forward to shoulder height. Step 3: Keep arms straight. Step 4: Lower with control.",
    photo: getExerciseImage("shoulders", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0034",
    name: "Concentration Curl",
    muscleGroup: "biceps",
    secondaryMuscles: [],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Step 1: Sit with elbow braced on thigh. Step 2: Curl weight up. Step 3: Squeeze bicep at top. Step 4: Lower slowly.",
    photo: getExerciseImage("biceps", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0035",
    name: "Rope Pushdown",
    muscleGroup: "triceps",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "intermediate",
    instructions: "Step 1: Stand at cable with rope attachment. Step 2: Push rope down and apart. Step 3: Squeeze triceps. Step 4: Control return.",
    photo: getExerciseImage("triceps", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0036",
    name: "Hack Squat",
    muscleGroup: "quadriceps",
    secondaryMuscles: [],
    equipment: "cable",
    difficulty: "advanced",
    instructions: "Step 1: Position in hack squat machine. Step 2: Squat down deeply. Step 3: Drive through heels. Step 4: Lock out legs.",
    photo: getExerciseImage("quadriceps", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0037",
    name: "Good Morning",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Step 1: Bar on upper back. Step 2: Hinge at hips keeping back flat. Step 3: Feel stretch in hamstrings. Step 4: Return to standing.",
    photo: getExerciseImage("hamstrings", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0038",
    name: "Glute Bridge",
    muscleGroup: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "band",
    difficulty: "intermediate",
    instructions: "Step 1: Lie on back with knees bent. Step 2: Drive hips up squeezing glutes. Step 3: Hold at top. Step 4: Lower with control.",
    photo: getExerciseImage("glutes", 0),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0039",
    name: "Donkey Calf Raise",
    muscleGroup: "calves",
    secondaryMuscles: [],
    equipment: "kettlebell",
    difficulty: "advanced",
    instructions: "Step 1: Bend at hips with toes on platform. Step 2: Raise heels as high as possible. Step 3: Hold at top. Step 4: Lower with control.",
    photo: getExerciseImage("calves", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
  {
    id: "ex_0040",
    name: "Plank",
    muscleGroup: "abs",
    secondaryMuscles: [],
    equipment: "bench",
    difficulty: "beginner",
    instructions: "Step 1: Hold body in straight line on forearms. Step 2: Keep core tight. Step 3: Don't let hips sag. Step 4: Breathe steadily.",
    photo: getExerciseImage("abs", 3),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  },
];

for (let i = 41; i <= 200; i++) {
  const muscleGroups: MuscleGroup[] = ["chest", "back", "shoulders", "biceps", "triceps", "quadriceps", "hamstrings", "glutes", "calves", "abs"];
  const equipment: ("barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "band" | "kettlebell" | "bench")[] = ["barbell", "dumbbell", "machine", "cable", "bodyweight", "band", "kettlebell", "bench"];
  const difficulties: ("beginner" | "intermediate" | "advanced")[] = ["beginner", "intermediate", "advanced"];
  
  const muscleGroup = muscleGroups[(i - 1) % muscleGroups.length];
  const secondaryMuscle = muscleGroups[i % muscleGroups.length];
  const equipmentType = equipment[(i - 1) % equipment.length];
  const difficulty = difficulties[(i - 1) % difficulties.length];
  
  EXERCISES.push({
    id: `ex_${String(i).padStart(4, "0")}`,
    name: `${muscleGroup.charAt(0).toUpperCase() + muscleGroup.slice(1)} Exercise ${i}`,
    muscleGroup,
    secondaryMuscles: [secondaryMuscle],
    equipment: equipmentType,
    difficulty,
    instructions: `Step 1: Proper setup and positioning. Step 2: Execute movement with control. Step 3: Squeeze target muscle. Step 4: Return to start position.`,
    photo: getExerciseImage(muscleGroup, Math.floor(i / 10)),
    tags: ["strength", "hypertrophy"],
    isCustom: false,
  });
}
